
services:
  db:
    image: postgres:latest
    container_name: to_do_app_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    image: to_do_app_image
    container_name: to_do_app
    restart: always
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.multistage
    depends_on:
      - db
    env_file:
      - .env  # Load env variables into the app
    ports:
      - "8080:8080"