name: Build and Deploy to Cloud Run

env:
  DOCKER_IMAGE_DB_URL: "${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/deploy-images/to-do-app-db:latest"
  DOCKER_IMAGE_APP_URL: "${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/deploy-images/to-do-app:latest"

on: [push]
# on:
#   push:
#     branches:
#       - main
#       - stg



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Clones the repository into the workflow’s runner environment.
    - name: Checkout code
      uses: actions/checkout@v3     

    # Enables the workflow to execute Google Cloud CLI commands
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ secrets.PROJECT_ID }}

    # Install and configure the Google Cloud SDK (gcloud)
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2   
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev
        gcloud auth print-access-token | sudo docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_LOCATION }}-docker.pkg.dev

    - name: Build Docker images
      run: |
        echo "${{ secrets.ENV_FILE }}" >> api/deploy/.env
        docker compose -f api/deploy/docker-compose.yml up -d --build
        docker tag postgres ${{ env.DOCKER_IMAGE_DB_URL }}
        docker tag to_do_app_image ${{ env.DOCKER_IMAGE_APP_URL }}
        docker image list

    - name: Push Database Docker image
      run: docker push ${{ env.DOCKER_IMAGE_DB_URL }}

    - name: Push App Docker image
      run: docker push ${{ env.DOCKER_IMAGE_APP_URL }}

    - name: Deploy Database to Cloud Run
      run: |
        gcloud run deploy to-do-app-database-service \
          --image ${{ env.DOCKER_IMAGE_DB_URL }} \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated

    - name: Deploy App to Cloud Run
      run: |
        gcloud run deploy to-do-app-service \
          --image ${{ env.DOCKER_IMAGE_APP_URL }} \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated